package GUI;

import GUI.model.Domino;
import core.mediator.Game;
import core.mediator.MediatorGame;
import game.logic.interfaces.Player;
import game.logic.interfaces.Hand;
import java.util.ArrayList;
import java.util.List;
import model.Piece;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lucas
 */
public class HandPlayer extends javax.swing.JPanel implements Player {

    /**
     * Creates new form HandPlayer
     */
    private Hand<Piece> hand;
    private List<Domino> dominos;
    private MediatorGame mediator = Game.getInstance();

    public HandPlayer(Hand<Piece> mao) {
        initComponents();

        this.hand = mao;
        pieceToDomino();

        for (Domino domino : dominos) {
            add(domino);
        }
    }

    private void pieceToDomino() {
        dominos = new ArrayList<>();
        dominos.add(new Domino(getClass().getResource("/Resources/r-domino0-1.png").getFile()));
        dominos.add(new Domino(getClass().getResource("/Resources/r-domino0-2.png").getFile()));
        dominos.add(new Domino(getClass().getResource("/Resources/r-domino0-3.png").getFile()));
    }

    private void addDomino(Piece piece) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void takeFromStack() {
        Piece piece = mediator.takeStack();
        hand.add(piece);
        addDomino(piece);
    }

    @Override
    public Piece putOnBoard() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void doMove() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Hand<Piece> showHand() {
        return hand;
    }
}
