/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.casa.*;

/**
 *
 * @author lucas
 */
public class Tabuleiro extends javax.swing.JPanel {

    /**
     * Creates new form Tabuleiro
     */
    public Tabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Casa22 = new Casa();
        jLabel6 = new javax.swing.JLabel();
        Casa23 = new Casa();
        jLabel7 = new javax.swing.JLabel();
        Casa24 = new Casa();
        jLabel8 = new javax.swing.JLabel();
        Casa25 = new Casa();
        jLabel9 = new javax.swing.JLabel();
        Casa26 = new Casa();
        jLabel10 = new javax.swing.JLabel();
        Casa28 = new Casa();
        jLabel14 = new javax.swing.JLabel();
        Casa29 = new Casa();
        jLabel11 = new javax.swing.JLabel();
        Casa30 = new Casa();
        jLabel12 = new javax.swing.JLabel();
        Casa27 = new Casa();
        jLabel13 = new javax.swing.JLabel();
        Casa20 = new Casa();
        jLabel15 = new javax.swing.JLabel();
        Casa19 = new Casa();
        jLabel16 = new javax.swing.JLabel();
        Casa18 = new Casa();
        jLabel17 = new javax.swing.JLabel();
        Casa17 = new Casa();
        jLabel18 = new javax.swing.JLabel();
        Casa16 = new Casa();
        jLabel19 = new javax.swing.JLabel();
        Casa15 = new Casa();
        jLabel20 = new javax.swing.JLabel();
        Casa14 = new Casa();
        jLabel21 = new javax.swing.JLabel();
        Casa13 = new Casa();
        jLabel22 = new javax.swing.JLabel();
        Casa12 = new Casa();
        jLabel23 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        Casa1.setLayout(new javax.swing.BoxLayout(Casa1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setText("Casa1");
        Casa1.add(jLabel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(Casa1, gridBagConstraints);

        jLabel5.setText("Casa21");

        javax.swing.GroupLayout Casa21Layout = new javax.swing.GroupLayout(Casa21);
        Casa21.setLayout(Casa21Layout);
        Casa21Layout.setHorizontalGroup(
            Casa21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(Casa21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa21Layout.setVerticalGroup(
            Casa21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
            .addGroup(Casa21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(Casa21, gridBagConstraints);

        jLabel4.setText("Casa31");

        javax.swing.GroupLayout Casa31Layout = new javax.swing.GroupLayout(Casa31);
        Casa31.setLayout(Casa31Layout);
        Casa31Layout.setHorizontalGroup(
            Casa31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(Casa31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa31Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa31Layout.setVerticalGroup(
            Casa31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
            .addGroup(Casa31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa31Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 0;
        add(Casa31, gridBagConstraints);

        Casa11.setLayout(new javax.swing.BoxLayout(Casa11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Casa11");
        Casa11.add(jLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        add(Casa11, gridBagConstraints);

        jLabel6.setText("Casa22");

        javax.swing.GroupLayout Casa22Layout = new javax.swing.GroupLayout(Casa22);
        Casa22.setLayout(Casa22Layout);
        Casa22Layout.setHorizontalGroup(
            Casa22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa22Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa22Layout.setVerticalGroup(
            Casa22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa22Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(Casa22, gridBagConstraints);

        jLabel7.setText("Casa23");

        javax.swing.GroupLayout Casa23Layout = new javax.swing.GroupLayout(Casa23);
        Casa23.setLayout(Casa23Layout);
        Casa23Layout.setHorizontalGroup(
            Casa23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa23Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa23Layout.setVerticalGroup(
            Casa23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa23Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(Casa23, gridBagConstraints);

        jLabel8.setText("Casa24");

        javax.swing.GroupLayout Casa24Layout = new javax.swing.GroupLayout(Casa24);
        Casa24.setLayout(Casa24Layout);
        Casa24Layout.setHorizontalGroup(
            Casa24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa24Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa24Layout.setVerticalGroup(
            Casa24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa24Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        add(Casa24, gridBagConstraints);

        jLabel9.setText("Casa25");

        javax.swing.GroupLayout Casa25Layout = new javax.swing.GroupLayout(Casa25);
        Casa25.setLayout(Casa25Layout);
        Casa25Layout.setHorizontalGroup(
            Casa25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa25Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa25Layout.setVerticalGroup(
            Casa25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa25Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        add(Casa25, gridBagConstraints);

        jLabel10.setText("Casa26");

        javax.swing.GroupLayout Casa26Layout = new javax.swing.GroupLayout(Casa26);
        Casa26.setLayout(Casa26Layout);
        Casa26Layout.setHorizontalGroup(
            Casa26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa26Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa26Layout.setVerticalGroup(
            Casa26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa26Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        add(Casa26, gridBagConstraints);

        jLabel14.setText("Casa28");

        javax.swing.GroupLayout Casa28Layout = new javax.swing.GroupLayout(Casa28);
        Casa28.setLayout(Casa28Layout);
        Casa28Layout.setHorizontalGroup(
            Casa28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa28Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa28Layout.setVerticalGroup(
            Casa28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa28Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        add(Casa28, gridBagConstraints);

        jLabel11.setText("Casa29");

        javax.swing.GroupLayout Casa29Layout = new javax.swing.GroupLayout(Casa29);
        Casa29.setLayout(Casa29Layout);
        Casa29Layout.setHorizontalGroup(
            Casa29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa29Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa29Layout.setVerticalGroup(
            Casa29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa29Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        add(Casa29, gridBagConstraints);

        jLabel12.setText("Casa30");

        javax.swing.GroupLayout Casa30Layout = new javax.swing.GroupLayout(Casa30);
        Casa30.setLayout(Casa30Layout);
        Casa30Layout.setHorizontalGroup(
            Casa30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa30Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa30Layout.setVerticalGroup(
            Casa30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa30Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        add(Casa30, gridBagConstraints);

        jLabel13.setText("Casa27");

        javax.swing.GroupLayout Casa27Layout = new javax.swing.GroupLayout(Casa27);
        Casa27.setLayout(Casa27Layout);
        Casa27Layout.setHorizontalGroup(
            Casa27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa27Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa27Layout.setVerticalGroup(
            Casa27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa27Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        add(Casa27, gridBagConstraints);

        javax.swing.GroupLayout CentroLayout = new javax.swing.GroupLayout(Centro);
        Centro.setLayout(CentroLayout);
        CentroLayout.setHorizontalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CentroLayout.setVerticalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 17;
        add(Centro, gridBagConstraints);

        jLabel15.setText("Casa20");

        javax.swing.GroupLayout Casa20Layout = new javax.swing.GroupLayout(Casa20);
        Casa20.setLayout(Casa20Layout);
        Casa20Layout.setHorizontalGroup(
            Casa20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa20Layout.setVerticalGroup(
            Casa20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(Casa20, gridBagConstraints);

        jLabel16.setText("Casa19");

        javax.swing.GroupLayout Casa19Layout = new javax.swing.GroupLayout(Casa19);
        Casa19.setLayout(Casa19Layout);
        Casa19Layout.setHorizontalGroup(
            Casa19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa19Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa19Layout.setVerticalGroup(
            Casa19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa19Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(Casa19, gridBagConstraints);

        jLabel17.setText("Casa18");

        javax.swing.GroupLayout Casa18Layout = new javax.swing.GroupLayout(Casa18);
        Casa18.setLayout(Casa18Layout);
        Casa18Layout.setHorizontalGroup(
            Casa18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa18Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa18Layout.setVerticalGroup(
            Casa18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa18Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        add(Casa18, gridBagConstraints);

        jLabel18.setText("Casa17");

        javax.swing.GroupLayout Casa17Layout = new javax.swing.GroupLayout(Casa17);
        Casa17.setLayout(Casa17Layout);
        Casa17Layout.setHorizontalGroup(
            Casa17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa17Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa17Layout.setVerticalGroup(
            Casa17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa17Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        add(Casa17, gridBagConstraints);

        jLabel19.setText("Casa16");

        javax.swing.GroupLayout Casa16Layout = new javax.swing.GroupLayout(Casa16);
        Casa16.setLayout(Casa16Layout);
        Casa16Layout.setHorizontalGroup(
            Casa16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Casa16Layout.setVerticalGroup(
            Casa16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Casa16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Casa16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        add(Casa16, gridBagConstraints);

        jLabel20.setText("Casa15");
        Casa15.add(jLabel20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        add(Casa15, gridBagConstraints);

        jLabel21.setText("Casa14");
        Casa14.add(jLabel21);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        add(Casa14, gridBagConstraints);

        jLabel22.setText("Casa13");
        Casa13.add(jLabel22);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        add(Casa13, gridBagConstraints);

        jLabel23.setText("Casa12");
        Casa12.add(jLabel23);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        add(Casa12, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JPanel Casa1 = new Casa();
    private final javax.swing.JPanel Casa11 = new Casa();
    private javax.swing.JPanel Casa12;
    private javax.swing.JPanel Casa13;
    private javax.swing.JPanel Casa14;
    private javax.swing.JPanel Casa15;
    private javax.swing.JPanel Casa16;
    private javax.swing.JPanel Casa17;
    private javax.swing.JPanel Casa18;
    private javax.swing.JPanel Casa19;
    private javax.swing.JPanel Casa20;
    private final javax.swing.JPanel Casa21 = new Casa();
    private javax.swing.JPanel Casa22;
    private javax.swing.JPanel Casa23;
    private javax.swing.JPanel Casa24;
    private javax.swing.JPanel Casa25;
    private javax.swing.JPanel Casa26;
    private javax.swing.JPanel Casa27;
    private javax.swing.JPanel Casa28;
    private javax.swing.JPanel Casa29;
    private javax.swing.JPanel Casa30;
    private final javax.swing.JPanel Casa31 = new Casa();
    private final javax.swing.JPanel Centro = new javax.swing.JPanel();
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
