package GUI.Hand;

import GUI.model.Domino;
import game.logic.interfaces.Player;
import game.logic.interfaces.Hand;
import model.Piece;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lucas
 */
public class HandPlayer extends GUI.model.HandGUI implements Player {

    private int point;

    public HandPlayer(Hand<Piece> hand) {
        super(hand);

        piecesToDomino(false);

        for (Domino domino : dominos) {
            add(domino);
        }

        this.point = 0;
        for (int i = 0; i < hand.qtdHand(); i++) {
            Piece piece = (Piece) hand.show(i);
            this.point += piece.getPoint();
        }
    }

    @Override
    public void addDomino(Piece piece) {
        this.hand.add(piece);
        Domino domino = piecesToDomino(piece, false);
        this.dominos.add(domino);
        add(domino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void takeFromStack() {
        Piece piece = mediator.takeStack();
        this.point += piece.getPoint();
        addDomino(piece);
    }

    @Override
    public Piece putOnBoard() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void doMove() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Hand<Piece> showHand() {
        return hand;
    }

    @Override
    public int getPoint() {
        return this.point;
    }
}
